/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BilingualText { 'en' : string, 'hi' : string }
export interface BlogPost {
  'id' : bigint,
  'title' : BilingualText,
  'content' : BilingualText,
  'published' : boolean,
  'createdAt' : Timestamp,
  'slug' : string,
  'excerpt' : BilingualText,
  'image' : [] | [ExternalBlob],
}
export interface Booking {
  'id' : bigint,
  'bookingCategory' : [] | [BookingCategory],
  'languagePreference' : LanguagePreference,
  'paymentReferenceId' : [] | [string],
  'serviceType' : string,
  'paymentStatus' : [] | [PaymentStatus],
  'name' : string,
  'createdAt' : Timestamp,
  'email' : [] | [string],
  'donorMessage' : [] | [BilingualText],
  'upiVPA' : [] | [string],
  'advanceAmount' : [] | [bigint],
  'preferredDate' : string,
  'address' : string,
  'preferredTime' : string,
  'phone' : string,
  'specialNotes' : string,
}
export type BookingCategory = { 'booking' : null } |
  { 'donation' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'message' : string,
  'phone' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface FAQ {
  'id' : bigint,
  'question' : BilingualText,
  'displayOrder' : bigint,
  'answer' : BilingualText,
  'category' : string,
}
export interface GalleryItem {
  'id' : bigint,
  'title' : BilingualText,
  'createdAt' : Timestamp,
  'category' : string,
  'image' : ExternalBlob,
}
export type LanguagePreference = { 'hindi' : null } |
  { 'bilingual' : null } |
  { 'english' : null };
export interface Package {
  'id' : bigint,
  'priceMinRupees' : bigint,
  'displayOrder' : bigint,
  'name' : BilingualText,
  'includedItems' : Array<BilingualText>,
  'description' : BilingualText,
  'priceMaxRupees' : bigint,
}
export type PaymentStatus = { 'pendingVerification' : null } |
  { 'verified' : null } |
  { 'notApplicable' : null } |
  { 'failed' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Review {
  'id' : bigint,
  'createdAt' : Timestamp,
  'reviewerName' : string,
  'rating' : bigint,
  'testimonial' : BilingualText,
}
export interface Service {
  'id' : bigint,
  'displayOrder' : bigint,
  'name' : BilingualText,
  'description' : BilingualText,
  'category' : ServiceCategory,
}
export interface ServiceArea { 'id' : bigint, 'name' : string }
export type ServiceCategory = { 'grahaDoshShanti' : null } |
  { 'jeevanSamskar' : null } |
  { 'jyotishServices' : null } |
  { 'vedicPujaHavan' : null };
export interface SiteConfig {
  'sankalp' : BilingualText,
  'tagline' : BilingualText,
  'socialLinks' : Array<SocialLink>,
  'upiPayeeName' : [] | [string],
  'upiNote' : [] | [string],
  'upiVPA' : [] | [string],
  'panditName' : BilingualText,
  'contactPhone' : string,
}
export interface SocialLink { 'url' : string, 'name' : string }
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__blogPosts' : ActorMethod<[], any>,
  '__bookings' : ActorMethod<[], any>,
  '__contactSubmissions' : ActorMethod<[], any>,
  '__faqs' : ActorMethod<[], any>,
  '__gallery' : ActorMethod<[], any>,
  '__idCounters' : ActorMethod<[], any>,
  '__packages' : ActorMethod<[], any>,
  '__reviews' : ActorMethod<[], any>,
  '__serviceAreas' : ActorMethod<[], any>,
  '__services' : ActorMethod<[], any>,
  '__siteConfig' : ActorMethod<[], any>,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      string,
      string,
      string,
      string,
      LanguagePreference,
      string,
      [] | [string],
      [] | [bigint],
      [] | [PaymentStatus],
      [] | [string],
      [] | [BookingCategory],
      [] | [BilingualText],
    ],
    Booking
  >,
  'createContactSubmission' : ActorMethod<
    [string, string, string],
    ContactSubmission
  >,
  'createDonation' : ActorMethod<
    [string, string, bigint, [] | [BilingualText], [] | [string]],
    Booking
  >,
  'createReview' : ActorMethod<[string, bigint, BilingualText], Review>,
  'execute' : ActorMethod<[string], Result>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getBookingsByPhone' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getFAQs' : ActorMethod<[], Array<FAQ>>,
  'getGallery' : ActorMethod<[], Array<GalleryItem>>,
  'getPackages' : ActorMethod<[], Array<Package>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  'getServiceAreas' : ActorMethod<[], Array<ServiceArea>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getServicesByCategory' : ActorMethod<[ServiceCategory], Array<Service>>,
  'getSiteConfig' : ActorMethod<[], [] | [SiteConfig]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'schema' : ActorMethod<[], string>,
  'updateBookingPaymentStatus' : ActorMethod<
    [bigint, PaymentStatus],
    [] | [Booking]
  >,
  'updateSiteConfig' : ActorMethod<[string, string, string], [] | [SiteConfig]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];