/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LanguagePreference = IDL.Variant({
  'hindi' : IDL.Null,
  'bilingual' : IDL.Null,
  'english' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pendingVerification' : IDL.Null,
  'verified' : IDL.Null,
  'notApplicable' : IDL.Null,
  'failed' : IDL.Null,
});
export const BookingCategory = IDL.Variant({
  'booking' : IDL.Null,
  'donation' : IDL.Null,
});
export const BilingualText = IDL.Record({ 'en' : IDL.Text, 'hi' : IDL.Text });
export const Timestamp = IDL.Nat;
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'bookingCategory' : IDL.Opt(BookingCategory),
  'languagePreference' : LanguagePreference,
  'paymentReferenceId' : IDL.Opt(IDL.Text),
  'serviceType' : IDL.Text,
  'paymentStatus' : IDL.Opt(PaymentStatus),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Opt(IDL.Text),
  'donorMessage' : IDL.Opt(BilingualText),
  'upiVPA' : IDL.Opt(IDL.Text),
  'advanceAmount' : IDL.Opt(IDL.Nat),
  'preferredDate' : IDL.Text,
  'address' : IDL.Text,
  'preferredTime' : IDL.Text,
  'phone' : IDL.Text,
  'specialNotes' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Timestamp,
  'reviewerName' : IDL.Text,
  'rating' : IDL.Nat,
  'testimonial' : BilingualText,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : BilingualText,
  'content' : BilingualText,
  'published' : IDL.Bool,
  'createdAt' : Timestamp,
  'slug' : IDL.Text,
  'excerpt' : BilingualText,
  'image' : IDL.Opt(ExternalBlob),
});
export const FAQ = IDL.Record({
  'id' : IDL.Nat,
  'question' : BilingualText,
  'displayOrder' : IDL.Nat,
  'answer' : BilingualText,
  'category' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : BilingualText,
  'createdAt' : Timestamp,
  'category' : IDL.Text,
  'image' : ExternalBlob,
});
export const Package = IDL.Record({
  'id' : IDL.Nat,
  'priceMinRupees' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'name' : BilingualText,
  'includedItems' : IDL.Vec(BilingualText),
  'description' : BilingualText,
  'priceMaxRupees' : IDL.Nat,
});
export const ServiceCategory = IDL.Variant({
  'grahaDoshShanti' : IDL.Null,
  'jeevanSamskar' : IDL.Null,
  'jyotishServices' : IDL.Null,
  'vedicPujaHavan' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'name' : BilingualText,
  'description' : BilingualText,
  'category' : ServiceCategory,
});
export const ServiceArea = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const SocialLink = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
export const SiteConfig = IDL.Record({
  'sankalp' : BilingualText,
  'tagline' : BilingualText,
  'socialLinks' : IDL.Vec(SocialLink),
  'upiPayeeName' : IDL.Opt(IDL.Text),
  'upiNote' : IDL.Opt(IDL.Text),
  'upiVPA' : IDL.Opt(IDL.Text),
  'panditName' : BilingualText,
  'contactPhone' : IDL.Text,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__blogPosts' : IDL.Func([], [IDL.Reserved], ['query']),
  '__bookings' : IDL.Func([], [IDL.Reserved], ['query']),
  '__contactSubmissions' : IDL.Func([], [IDL.Reserved], ['query']),
  '__faqs' : IDL.Func([], [IDL.Reserved], ['query']),
  '__gallery' : IDL.Func([], [IDL.Reserved], ['query']),
  '__idCounters' : IDL.Func([], [IDL.Reserved], ['query']),
  '__packages' : IDL.Func([], [IDL.Reserved], ['query']),
  '__reviews' : IDL.Func([], [IDL.Reserved], ['query']),
  '__serviceAreas' : IDL.Func([], [IDL.Reserved], ['query']),
  '__services' : IDL.Func([], [IDL.Reserved], ['query']),
  '__siteConfig' : IDL.Func([], [IDL.Reserved], ['query']),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        LanguagePreference,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(PaymentStatus),
        IDL.Opt(IDL.Text),
        IDL.Opt(BookingCategory),
        IDL.Opt(BilingualText),
      ],
      [Booking],
      [],
    ),
  'createContactSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ContactSubmission],
      [],
    ),
  'createDonation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(BilingualText), IDL.Opt(IDL.Text)],
      [Booking],
      [],
    ),
  'createReview' : IDL.Func([IDL.Text, IDL.Nat, BilingualText], [Review], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
  'getBookingsByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
  'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getGallery' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getServiceAreas' : IDL.Func([], [IDL.Vec(ServiceArea)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getServicesByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'getSiteConfig' : IDL.Func([], [IDL.Opt(SiteConfig)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateBookingPaymentStatus' : IDL.Func(
      [IDL.Nat, PaymentStatus],
      [IDL.Opt(Booking)],
      [],
    ),
  'updateSiteConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(SiteConfig)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LanguagePreference = IDL.Variant({
    'hindi' : IDL.Null,
    'bilingual' : IDL.Null,
    'english' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pendingVerification' : IDL.Null,
    'verified' : IDL.Null,
    'notApplicable' : IDL.Null,
    'failed' : IDL.Null,
  });
  const BookingCategory = IDL.Variant({
    'booking' : IDL.Null,
    'donation' : IDL.Null,
  });
  const BilingualText = IDL.Record({ 'en' : IDL.Text, 'hi' : IDL.Text });
  const Timestamp = IDL.Nat;
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'bookingCategory' : IDL.Opt(BookingCategory),
    'languagePreference' : LanguagePreference,
    'paymentReferenceId' : IDL.Opt(IDL.Text),
    'serviceType' : IDL.Text,
    'paymentStatus' : IDL.Opt(PaymentStatus),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Opt(IDL.Text),
    'donorMessage' : IDL.Opt(BilingualText),
    'upiVPA' : IDL.Opt(IDL.Text),
    'advanceAmount' : IDL.Opt(IDL.Nat),
    'preferredDate' : IDL.Text,
    'address' : IDL.Text,
    'preferredTime' : IDL.Text,
    'phone' : IDL.Text,
    'specialNotes' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Timestamp,
    'reviewerName' : IDL.Text,
    'rating' : IDL.Nat,
    'testimonial' : BilingualText,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : BilingualText,
    'content' : BilingualText,
    'published' : IDL.Bool,
    'createdAt' : Timestamp,
    'slug' : IDL.Text,
    'excerpt' : BilingualText,
    'image' : IDL.Opt(ExternalBlob),
  });
  const FAQ = IDL.Record({
    'id' : IDL.Nat,
    'question' : BilingualText,
    'displayOrder' : IDL.Nat,
    'answer' : BilingualText,
    'category' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : BilingualText,
    'createdAt' : Timestamp,
    'category' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Package = IDL.Record({
    'id' : IDL.Nat,
    'priceMinRupees' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'name' : BilingualText,
    'includedItems' : IDL.Vec(BilingualText),
    'description' : BilingualText,
    'priceMaxRupees' : IDL.Nat,
  });
  const ServiceCategory = IDL.Variant({
    'grahaDoshShanti' : IDL.Null,
    'jeevanSamskar' : IDL.Null,
    'jyotishServices' : IDL.Null,
    'vedicPujaHavan' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'name' : BilingualText,
    'description' : BilingualText,
    'category' : ServiceCategory,
  });
  const ServiceArea = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const SocialLink = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const SiteConfig = IDL.Record({
    'sankalp' : BilingualText,
    'tagline' : BilingualText,
    'socialLinks' : IDL.Vec(SocialLink),
    'upiPayeeName' : IDL.Opt(IDL.Text),
    'upiNote' : IDL.Opt(IDL.Text),
    'upiVPA' : IDL.Opt(IDL.Text),
    'panditName' : BilingualText,
    'contactPhone' : IDL.Text,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__blogPosts' : IDL.Func([], [IDL.Reserved], ['query']),
    '__bookings' : IDL.Func([], [IDL.Reserved], ['query']),
    '__contactSubmissions' : IDL.Func([], [IDL.Reserved], ['query']),
    '__faqs' : IDL.Func([], [IDL.Reserved], ['query']),
    '__gallery' : IDL.Func([], [IDL.Reserved], ['query']),
    '__idCounters' : IDL.Func([], [IDL.Reserved], ['query']),
    '__packages' : IDL.Func([], [IDL.Reserved], ['query']),
    '__reviews' : IDL.Func([], [IDL.Reserved], ['query']),
    '__serviceAreas' : IDL.Func([], [IDL.Reserved], ['query']),
    '__services' : IDL.Func([], [IDL.Reserved], ['query']),
    '__siteConfig' : IDL.Func([], [IDL.Reserved], ['query']),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          LanguagePreference,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(PaymentStatus),
          IDL.Opt(IDL.Text),
          IDL.Opt(BookingCategory),
          IDL.Opt(BilingualText),
        ],
        [Booking],
        [],
      ),
    'createContactSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ContactSubmission],
        [],
      ),
    'createDonation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(BilingualText),
          IDL.Opt(IDL.Text),
        ],
        [Booking],
        [],
      ),
    'createReview' : IDL.Func([IDL.Text, IDL.Nat, BilingualText], [Review], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
    'getBookingsByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
    'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getGallery' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getServiceAreas' : IDL.Func([], [IDL.Vec(ServiceArea)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getServicesByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getSiteConfig' : IDL.Func([], [IDL.Opt(SiteConfig)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateBookingPaymentStatus' : IDL.Func(
        [IDL.Nat, PaymentStatus],
        [IDL.Opt(Booking)],
        [],
      ),
    'updateSiteConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(SiteConfig)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };