/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface BlogPost {
    id: bigint;
    title: BilingualText;
    content: BilingualText;
    published: boolean;
    createdAt: Timestamp;
    slug: string;
    excerpt: BilingualText;
    image?: ExternalBlob;
}
export interface FAQ {
    id: bigint;
    question: BilingualText;
    displayOrder: bigint;
    answer: BilingualText;
    category: string;
}
export type Timestamp = bigint;
export interface ServiceArea {
    id: bigint;
    name: string;
}
export interface ContactSubmission {
    id: bigint;
    name: string;
    createdAt: Timestamp;
    message: string;
    phone: string;
}
export interface SiteConfig {
    sankalp: BilingualText;
    tagline: BilingualText;
    socialLinks: Array<SocialLink>;
    upiPayeeName?: string;
    upiNote?: string;
    upiVPA?: string;
    panditName: BilingualText;
    contactPhone: string;
}
export interface SocialLink {
    url: string;
    name: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Service {
    id: bigint;
    displayOrder: bigint;
    name: BilingualText;
    description: BilingualText;
    category: ServiceCategory;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Package {
    id: bigint;
    priceMinRupees: bigint;
    displayOrder: bigint;
    name: BilingualText;
    includedItems: Array<BilingualText>;
    description: BilingualText;
    priceMaxRupees: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface BilingualText {
    en: string;
    hi: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface GalleryItem {
    id: bigint;
    title: BilingualText;
    createdAt: Timestamp;
    category: string;
    image: ExternalBlob;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface Booking {
    id: bigint;
    bookingCategory?: BookingCategory;
    languagePreference: LanguagePreference;
    paymentReferenceId?: string;
    serviceType: string;
    paymentStatus?: PaymentStatus;
    name: string;
    createdAt: Timestamp;
    email?: string;
    donorMessage?: BilingualText;
    upiVPA?: string;
    advanceAmount?: bigint;
    preferredDate: string;
    address: string;
    preferredTime: string;
    phone: string;
    specialNotes: string;
}
export interface Review {
    id: bigint;
    createdAt: Timestamp;
    reviewerName: string;
    rating: bigint;
    testimonial: BilingualText;
}
export enum BookingCategory {
    booking = "booking",
    donation = "donation"
}
export enum LanguagePreference {
    hindi = "hindi",
    bilingual = "bilingual",
    english = "english"
}
export enum PaymentStatus {
    pendingVerification = "pendingVerification",
    verified = "verified",
    notApplicable = "notApplicable",
    failed = "failed"
}
export enum ServiceCategory {
    grahaDoshShanti = "grahaDoshShanti",
    jeevanSamskar = "jeevanSamskar",
    jyotishServices = "jyotishServices",
    vedicPujaHavan = "vedicPujaHavan"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __blogPosts(): Promise<any>;
    __bookings(): Promise<any>;
    __contactSubmissions(): Promise<any>;
    __faqs(): Promise<any>;
    __gallery(): Promise<any>;
    __idCounters(): Promise<any>;
    __packages(): Promise<any>;
    __reviews(): Promise<any>;
    __serviceAreas(): Promise<any>;
    __services(): Promise<any>;
    __siteConfig(): Promise<any>;
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBooking(name: string, phone: string, email: string | null, serviceType: string, preferredDate: string, preferredTime: string, address: string, languagePreference: LanguagePreference, specialNotes: string, upiVPA: string | null, advanceAmount: bigint | null, paymentStatus: PaymentStatus | null, paymentReferenceId: string | null, bookingCategory: BookingCategory | null, donorMessage: BilingualText | null): Promise<Booking>;
    createContactSubmission(name: string, phone: string, message: string): Promise<ContactSubmission>;
    createDonation(donorName: string, donorPhone: string, amount: bigint, donorMessage: BilingualText | null, paymentReferenceId: string | null): Promise<Booking>;
    createReview(reviewerName: string, rating: bigint, testimonial: BilingualText): Promise<Review>;
    execute(qJson: string): Promise<Result>;
    getBlogPost(slug: string): Promise<BlogPost | null>;
    getBlogPosts(): Promise<Array<BlogPost>>;
    getBookings(): Promise<Array<Booking>>;
    getBookingsByPhone(phone: string): Promise<Array<Booking>>;
    getCallerUserRole(): Promise<UserRole>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getFAQs(): Promise<Array<FAQ>>;
    getGallery(): Promise<Array<GalleryItem>>;
    getPackages(): Promise<Array<Package>>;
    getReviews(): Promise<Array<Review>>;
    getService(id: bigint): Promise<Service | null>;
    getServiceAreas(): Promise<Array<ServiceArea>>;
    getServices(): Promise<Array<Service>>;
    getServicesByCategory(category: ServiceCategory): Promise<Array<Service>>;
    getSiteConfig(): Promise<SiteConfig | null>;
    isCallerAdmin(): Promise<boolean>;
    schema(): Promise<string>;
    updateBookingPaymentStatus(bookingId: bigint, newStatus: PaymentStatus): Promise<Booking | null>;
    updateSiteConfig(upiVPA: string, upiPayeeName: string, upiNote: string): Promise<SiteConfig | null>;
}
import type { BilingualText as _BilingualText, BlogPost as _BlogPost, Booking as _Booking, BookingCategory as _BookingCategory, Cell as _Cell, Error as _Error, ExternalBlob as _ExternalBlob, GalleryItem as _GalleryItem, LanguagePreference as _LanguagePreference, PaymentStatus as _PaymentStatus, Result as _Result, Result__1 as _Result__1, Service as _Service, ServiceCategory as _ServiceCategory, SiteConfig as _SiteConfig, SocialLink as _SocialLink, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __blogPosts(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__blogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__blogPosts();
            return result;
        }
    }
    async __bookings(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__bookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__bookings();
            return result;
        }
    }
    async __contactSubmissions(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__contactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__contactSubmissions();
            return result;
        }
    }
    async __faqs(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__faqs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__faqs();
            return result;
        }
    }
    async __gallery(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__gallery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__gallery();
            return result;
        }
    }
    async __idCounters(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__idCounters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__idCounters();
            return result;
        }
    }
    async __packages(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__packages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__packages();
            return result;
        }
    }
    async __reviews(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__reviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__reviews();
            return result;
        }
    }
    async __serviceAreas(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__serviceAreas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__serviceAreas();
            return result;
        }
    }
    async __services(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__services();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__services();
            return result;
        }
    }
    async __siteConfig(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__siteConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__siteConfig();
            return result;
        }
    }
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: string, arg1: string, arg2: string | null, arg3: string, arg4: string, arg5: string, arg6: string, arg7: LanguagePreference, arg8: string, arg9: string | null, arg10: bigint | null, arg11: PaymentStatus | null, arg12: string | null, arg13: BookingCategory | null, arg14: BilingualText | null): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, to_candid_LanguagePreference_n15(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg14));
                return from_candid_Booking_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, to_candid_LanguagePreference_n15(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg14));
            return from_candid_Booking_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createContactSubmission(arg0: string, arg1: string, arg2: string): Promise<ContactSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.createContactSubmission(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContactSubmission(arg0, arg1, arg2);
            return result;
        }
    }
    async createDonation(arg0: string, arg1: string, arg2: bigint, arg3: BilingualText | null, arg4: string | null): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createDonation(arg0, arg1, arg2, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Booking_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDonation(arg0, arg1, arg2, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Booking_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReview(arg0: string, arg1: bigint, arg2: BilingualText): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.createReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReview(arg0, arg1, arg2);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByPhone(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByPhone(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByPhone(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return result;
        }
    }
    async getFAQs(): Promise<Array<FAQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFAQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFAQs();
            return result;
        }
    }
    async getGallery(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGallery();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGallery();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackages();
            return result;
        }
    }
    async getReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews();
            return result;
        }
    }
    async getService(arg0: bigint): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceAreas(): Promise<Array<ServiceArea>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceAreas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceAreas();
            return result;
        }
    }
    async getServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServices();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServices();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServicesByCategory(arg0: ServiceCategory): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicesByCategory(to_candid_ServiceCategory_n63(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicesByCategory(to_candid_ServiceCategory_n63(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteConfig(): Promise<SiteConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteConfig();
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteConfig();
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateBookingPaymentStatus(arg0: bigint, arg1: PaymentStatus): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingPaymentStatus(arg0, to_candid_PaymentStatus_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingPaymentStatus(arg0, to_candid_PaymentStatus_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSiteConfig(arg0: string, arg1: string, arg2: string): Promise<SiteConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteConfig(arg0, arg1, arg2);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteConfig(arg0, arg1, arg2);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_BlogPost_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): Promise<BlogPost> {
    return await from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_BookingCategory_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingCategory): BookingCategory {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryItem_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): Promise<GalleryItem> {
    return await from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_LanguagePreference_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LanguagePreference): LanguagePreference {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_SiteConfig_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteConfig): SiteConfig {
    return from_candid_record_n67(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingCategory]): BookingCategory | null {
    return value.length === 0 ? null : from_candid_BookingCategory_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentStatus]): PaymentStatus | null {
    return value.length === 0 ? null : from_candid_PaymentStatus_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BilingualText]): BilingualText | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): Promise<BlogPost | null> {
    return value.length === 0 ? null : await from_candid_BlogPost_n46(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : from_candid_Service_n58(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SiteConfig]): SiteConfig | null {
    return value.length === 0 ? null : from_candid_SiteConfig_n66(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bookingCategory: [] | [_BookingCategory];
    languagePreference: _LanguagePreference;
    paymentReferenceId: [] | [string];
    serviceType: string;
    paymentStatus: [] | [_PaymentStatus];
    name: string;
    createdAt: _Timestamp;
    email: [] | [string];
    donorMessage: [] | [_BilingualText];
    upiVPA: [] | [string];
    advanceAmount: [] | [bigint];
    preferredDate: string;
    address: string;
    preferredTime: string;
    phone: string;
    specialNotes: string;
}): {
    id: bigint;
    bookingCategory?: BookingCategory;
    languagePreference: LanguagePreference;
    paymentReferenceId?: string;
    serviceType: string;
    paymentStatus?: PaymentStatus;
    name: string;
    createdAt: Timestamp;
    email?: string;
    donorMessage?: BilingualText;
    upiVPA?: string;
    advanceAmount?: bigint;
    preferredDate: string;
    address: string;
    preferredTime: string;
    phone: string;
    specialNotes: string;
} {
    return {
        id: value.id,
        bookingCategory: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.bookingCategory)),
        languagePreference: from_candid_LanguagePreference_n30(_uploadFile, _downloadFile, value.languagePreference),
        paymentReferenceId: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.paymentReferenceId)),
        serviceType: value.serviceType,
        paymentStatus: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.paymentStatus)),
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.email)),
        donorMessage: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.donorMessage)),
        upiVPA: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.upiVPA)),
        advanceAmount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.advanceAmount)),
        preferredDate: value.preferredDate,
        address: value.address,
        preferredTime: value.preferredTime,
        phone: value.phone,
        specialNotes: value.specialNotes
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n39(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n43(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
async function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: _BilingualText;
    content: _BilingualText;
    published: boolean;
    createdAt: _Timestamp;
    slug: string;
    excerpt: _BilingualText;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    title: BilingualText;
    content: BilingualText;
    published: boolean;
    createdAt: Timestamp;
    slug: string;
    excerpt: BilingualText;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        published: value.published,
        createdAt: value.createdAt,
        slug: value.slug,
        excerpt: value.excerpt,
        image: record_opt_to_undefined(await from_candid_opt_n48(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: _BilingualText;
    createdAt: _Timestamp;
    category: string;
    image: _ExternalBlob;
}): Promise<{
    id: bigint;
    title: BilingualText;
    createdAt: Timestamp;
    category: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        category: value.category,
        image: await from_candid_ExternalBlob_n49(_uploadFile, _downloadFile, value.image)
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    displayOrder: bigint;
    name: _BilingualText;
    description: _BilingualText;
    category: _ServiceCategory;
}): {
    id: bigint;
    displayOrder: bigint;
    name: BilingualText;
    description: BilingualText;
    category: ServiceCategory;
} {
    return {
        id: value.id,
        displayOrder: value.displayOrder,
        name: value.name,
        description: value.description,
        category: from_candid_ServiceCategory_n60(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sankalp: _BilingualText;
    tagline: _BilingualText;
    socialLinks: Array<_SocialLink>;
    upiPayeeName: [] | [string];
    upiNote: [] | [string];
    upiVPA: [] | [string];
    panditName: _BilingualText;
    contactPhone: string;
}): {
    sankalp: BilingualText;
    tagline: BilingualText;
    socialLinks: Array<SocialLink>;
    upiPayeeName?: string;
    upiNote?: string;
    upiVPA?: string;
    panditName: BilingualText;
    contactPhone: string;
} {
    return {
        sankalp: value.sankalp,
        tagline: value.tagline,
        socialLinks: value.socialLinks,
        upiPayeeName: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.upiPayeeName)),
        upiNote: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.upiNote)),
        upiVPA: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.upiVPA)),
        panditName: value.panditName,
        contactPhone: value.contactPhone
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    booking: null;
} | {
    donation: null;
}): BookingCategory {
    return "booking" in value ? BookingCategory.booking : "donation" in value ? BookingCategory.donation : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hindi: null;
} | {
    bilingual: null;
} | {
    english: null;
}): LanguagePreference {
    return "hindi" in value ? LanguagePreference.hindi : "bilingual" in value ? LanguagePreference.bilingual : "english" in value ? LanguagePreference.english : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingVerification: null;
} | {
    verified: null;
} | {
    notApplicable: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pendingVerification" in value ? PaymentStatus.pendingVerification : "verified" in value ? PaymentStatus.verified : "notApplicable" in value ? PaymentStatus.notApplicable : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grahaDoshShanti: null;
} | {
    jeevanSamskar: null;
} | {
    jyotishServices: null;
} | {
    vedicPujaHavan: null;
}): ServiceCategory {
    return "grahaDoshShanti" in value ? ServiceCategory.grahaDoshShanti : "jeevanSamskar" in value ? ServiceCategory.jeevanSamskar : "jyotishServices" in value ? ServiceCategory.jyotishServices : "vedicPujaHavan" in value ? ServiceCategory.vedicPujaHavan : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n41(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Promise<Array<BlogPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BlogPost_n46(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n25(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Promise<Array<GalleryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryItem_n55(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n58(_uploadFile, _downloadFile, x));
}
function to_candid_BookingCategory_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingCategory): _BookingCategory {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_LanguagePreference_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LanguagePreference): _LanguagePreference {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus | null): [] | [_PaymentStatus] {
    return value === null ? candid_none() : candid_some(to_candid_PaymentStatus_n19(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingCategory | null): [] | [_BookingCategory] {
    return value === null ? candid_none() : candid_some(to_candid_BookingCategory_n22(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BilingualText | null): [] | [_BilingualText] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LanguagePreference): {
    hindi: null;
} | {
    bilingual: null;
} | {
    english: null;
} {
    return value == LanguagePreference.hindi ? {
        hindi: null
    } : value == LanguagePreference.bilingual ? {
        bilingual: null
    } : value == LanguagePreference.english ? {
        english: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pendingVerification: null;
} | {
    verified: null;
} | {
    notApplicable: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pendingVerification ? {
        pendingVerification: null
    } : value == PaymentStatus.verified ? {
        verified: null
    } : value == PaymentStatus.notApplicable ? {
        notApplicable: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingCategory): {
    booking: null;
} | {
    donation: null;
} {
    return value == BookingCategory.booking ? {
        booking: null
    } : value == BookingCategory.donation ? {
        donation: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    grahaDoshShanti: null;
} | {
    jeevanSamskar: null;
} | {
    jyotishServices: null;
} | {
    vedicPujaHavan: null;
} {
    return value == ServiceCategory.grahaDoshShanti ? {
        grahaDoshShanti: null
    } : value == ServiceCategory.jeevanSamskar ? {
        jeevanSamskar: null
    } : value == ServiceCategory.jyotishServices ? {
        jyotishServices: null
    } : value == ServiceCategory.vedicPujaHavan ? {
        vedicPujaHavan: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
